### ISSUE TITLE
Error loading base_model

### ISSUE THREAD

**Issue by jmauro** [realityforge/knife-cookbook-doc#15]
Hey,
I am trying to use this gem and I am having the following issue:
```
> knife cookbook doc ~/tmp/repository/cookbook-dev/raid
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- knife_cookbook_doc/base_model (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from /home/user/.gem/ruby/2.1.0/gems/knife-cookbook-doc-0.11.0/lib/chef/knife/cookbook_doc.rb:9:in `block in <class:CookbookDoc>'
        from /home/user/.gem/ruby/2.1.0/gems/chef-11.14.2/lib/chef/knife.rb:215:in `call'
        from /home/user/.gem/ruby/2.1.0/gems/chef-11.14.2/lib/chef/knife.rb:215:in `block in load_deps'
        from /home/user/.gem/ruby/2.1.0/gems/chef-11.14.2/lib/chef/knife.rb:214:in `each'
        from /home/user/.gem/ruby/2.1.0/gems/chef-11.14.2/lib/chef/knife.rb:214:in `load_deps'
        from /home/user/.gem/ruby/2.1.0/gems/chef-11.14.2/lib/chef/knife.rb:171:in `run'
        from /home/user/.gem/ruby/2.1.0/gems/chef-11.14.2/lib/chef/application/knife.rb:139:in `run'
        from /home/user/.gem/ruby/2.1.0/gems/chef-11.14.2/bin/knife:25:in `<top (required)>'
        from /home/user/.gem/ruby/2.1.0/bin/knife:23:in `load'
        from /home/user/.gem/ruby/2.1.0/bin/knife:23:in `<main>'
> gem list knife-cookbook-doc

*** LOCAL GEMS ***

knife-cookbook-doc (0.11.0)
> gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.1.2 (2014-05-08 patchlevel 95) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /home/user/.gem/ruby/2.1.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.1
  - EXECUTABLE DIRECTORY: /home/user/.gem/ruby/2.1.0/bin
  - SPEC CACHE DIRECTORY: /home/user/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/user/.gem/ruby/2.1.0
     - /var/lib/gems/2.1.0
     - /usr/share/rubygems-integration/2.1.0
     - /usr/share/rubygems-integration/2.1
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => 1
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc --verbose"
     - :benchmark => false
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/local/games
     - /usr/games
     - /sbin
     - /usr/sbin
     - /usr/local/sbin
> locate base_model
/home/user/.gem/ruby/2.1.0/gems/knife-cookbook-doc-0.11.0/lib/knife_cookbook_doc/base_model.rb
```
Any idea what could be the problem? Is that due the use of a GEM_PATH?

Regards,
JM

**Comment by philoserf** [comment]
@jmauro Is this still an issue?
@realityforge I will look at adding Travis CI for automated testing against more chef versions.

**Comment by jmauro** [comment]
Hey I haven't tried recently but let you know as soon as I get the chance
to check.

**Comment by realityforge** [comment]
Having a look at the CI that runs against many versions of chef. It seems it has been fixed. Feel free to re-open this issue if you find the latest version of the gem has not fixed it. 

Thanks!
