### ISSUE TITLE
knife cookbook doc fails if node attributes are referenced in light-weight resources.

### ISSUE THREAD

**Issue by RobertNorthard** [realityforge/knife-cookbook-doc#24]
Knife cookbook doc fails if node attributes are referenced in light-weight resources.

attribute :attribute_name, :kind_of => value, :default => **node['org_cb']['attr']**

**Comment by philoserf** [comment]
@RobertNorthard Are you willing to give us a Gist with a bit more detail. Perhaps the result of `knife -v`, a snippet from your `resources/[filename].rb`, and the command line you use to invoke `knife cookbook doc`.

**Comment by smedefind** [comment]
I'm running into this too.

Knife Output:
```
knife cookbook doc . -VV
/Users/smedefind/.rvm/gems/ruby-2.1.5/gems/chef-11.18.6/lib/chef/resource/lwrp_base.rb:141:in `node': undefined method `node' for nil:NilClass (NoMethodError)
        from /Users/smedefind/src/cookbooks/optoro_nagios/resources/s3_file.rb:36:in `build_native_from_file'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/knife_cookbook_doc/resource_model.rb:98:in `class_eval'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/knife_cookbook_doc/resource_model.rb:98:in `build_native_from_file'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/knife_cookbook_doc/resource_model.rb:8:in `initialize'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/knife_cookbook_doc/readme_model.rb:27:in `new'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/knife_cookbook_doc/readme_model.rb:27:in `block in initialize'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/knife_cookbook_doc/readme_model.rb:26:in `each'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/knife_cookbook_doc/readme_model.rb:26:in `initialize'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/chef/knife/cookbook_doc.rb:47:in `new'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/knife-cookbook-doc-0.14.0/lib/chef/knife/cookbook_doc.rb:47:in `run'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/chef-11.18.6/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/chef-11.18.6/lib/chef/knife.rb:174:in `run'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/chef-11.18.6/lib/chef/application/knife.rb:139:in `run'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/gems/chef-11.18.6/bin/knife:25:in `<top (required)>'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/bin/knife:23:in `load'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/bin/knife:23:in `<main>'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /Users/smedefind/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

Relevant section of code:
```ruby
34 attribute :checksum, kind_of: [String, NilClass], default: nil
35 attribute :backup, kind_of: [Integer, FalseClass], default: 5
36 if node['platform_family'] == 'windows'
37   attribute :inherits, kind_of: [TrueClass, FalseClass], default: true
38   attribute :rights, kind_of: Hash, default: nil
39 end
40
41  version = Chef::Version.new(Chef::VERSION[/^(\d+\.\d+\.\d+)/, 1])
```

**Comment by RobertNorthard** [comment]
Pull request, #29 should resolve the initial issue with the node object being undefined. However as the run_context is nill it won't be able to resolve any of the nodes attributes.

**Comment by bryan-buckland** [comment]
Any updates on handle node object in resources for documentation ?

**Comment by realityforge** [comment]
Not had time to work on this sorry 🙁
