### ISSUE TITLE
Chef 15 removed support for attributes in metadata.rb

### ISSUE THREAD

**Issue by grozan** [realityforge/knife-cookbook-doc#46]
Environment:

using `knife-cookbook-doc (0.26.0)`

chef environment
```
$ chef --version
Chef Development Kit Version: 4.0.60
chef-client version: 15.0.300
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 2.2.5
inspec version: 4.3.2
```

Relevant code or config:

The generation of the documentation of a brand new cookbook fails with

```
Traceback (most recent call last):
	10: from /usr/local/bin/knife:316:in `<main>'
	 9: from /usr/local/bin/knife:316:in `load'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/bin/knife:24:in `<top (required)>'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/application/knife.rb:162:in `run'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife.rb:221:in `run'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife.rb:473:in `run_with_pretty_exceptions'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/local_mode.rb:41:in `with_server_connectivity'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife.rb:474:in `block in run_with_pretty_exceptions'
	 2: from /Users/me/.chefdk/gem/ruby/2.6.0/gems/knife-cookbook-doc-0.26.0/lib/chef/knife/cookbook_doc.rb:53:in `run'
	 1: from /Users/me/.chefdk/gem/ruby/2.6.0/gems/knife-cookbook-doc-0.26.0/lib/chef/knife/cookbook_doc.rb:53:in `new'
/Users/me/.chefdk/gem/ruby/2.6.0/gems/knife-cookbook-doc-0.26.0/lib/knife_cookbook_doc/readme_model.rb:10:in `initialize': undefined method `empty?' for nil:NilClass (NoMethodError)
```

Problem description:

From the Chef release notes

```
attributes in metadata.rb
Chef Infra Client no longer processes attributes in the metadata.rb file.
Attributes could be defined in the metadata.rb file as a form of documentation, which would 
be shown when running knife cookbook show COOKBOOK_NAME. Often, these attribute
definitions would become out of sync with the attributes in the actual attributes files. Chef Infra 
Client 15 will no longer show these attributes when running knife cookbook show 
COOKBOOK_NAME and will instead throw a warning message upon upload. Foodcritic has 
warned against the use of attributes in the metadata.rb file since April 2017.
```
`Chef::Cookbook::Metadata` does not have `attributes` anymore

**Comment by grozan** [comment]
PR #47 opened
