### ISSUE TITLE
generating docs fail to load libraries from action_class

### ISSUE THREAD

**Issue by moodwrench** [realityforge/knife-cookbook-doc#48]
Environment:
```
Chef: 14.13.11
knife-cookbook-doc: 0.27.0
```

Relevant code or config:

cookbooks/mycookbook/resources/my_resource.rb
```
action_class do
    include MyLibrary
end
```

cookbooks/mycookbook/libraries/my_library.rb
```
module MyLibrary
  def code
  end
end
```

What happened:

```
$ chef exec knife cookbook doc . -VVV
INFO: Using configuration from /Users/myhome/.chef/knife.rb
Traceback (most recent call last):
	20: from /opt/chefdk/bin/knife:311:in `<main>'
	19: from /opt/chefdk/bin/knife:311:in `load'
	18: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/bin/knife:24:in `<top (required)>'
	17: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application/knife.rb:161:in `run'
	16: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/knife.rb:220:in `run'
	15: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/knife.rb:445:in `run_with_pretty_exceptions'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/knife.rb:446:in `block in run_with_pretty_exceptions'
	12: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/chef/knife/cookbook_doc.rb:53:in `run'
	11: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/chef/knife/cookbook_doc.rb:53:in `new'
	10: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/knife_cookbook_doc/readme_model.rb:26:in `initialize'
	 9: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/knife_cookbook_doc/readme_model.rb:26:in `each'
	 8: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/knife_cookbook_doc/readme_model.rb:27:in `block in initialize'
	 7: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/knife_cookbook_doc/readme_model.rb:27:in `new'
	 6: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/knife_cookbook_doc/resource_model.rb:8:in `initialize'
	 5: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/knife_cookbook_doc/resource_model.rb:111:in `build_native_from_file'
	 4: from /Users/myhome/.chefdk/gem/ruby/2.5.0/gems/knife-cookbook-doc-0.27.0/lib/knife_cookbook_doc/resource_model.rb:111:in `class_eval'
	 3: from /Users/myhome/git/chef-repo/cookbooks/mycookbook/resources/my_resource.rb:37:in `build_native_from_file'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource.rb:1120:in `action_class'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource.rb:1120:in `class_eval'
```

**Comment by limitusus** [comment]
This occurs with Chef 15.9.7 and gem 0.29.0 as well

**Comment by kommado** [comment]
Hello I have a fix for this issue, but I get permission denied when i try to push my branch, can you give me permissions for this or I can send the suggested fix in another way?

**Comment by realityforge** [comment]
Hi,

Generally we follow the [Github Pull Request Model](https://help.github.com/articles/about-pull-requests/) for
 contributions. See https://github.com/realityforge/knife-cookbook-doc/blob/master/CONTRIBUTING.md for further details - thanks ;)

**Comment by kommado** [comment]
Hello Peter,

I have read the Contribution guide, but I have a problem when I try to push
the branch with my changes (I get permission denied),
obviously I need to push a branch before I can initiate a pull request :).

Thanks in advance for your help.
